export enum UserRole {
  ADMIN = 'ADMIN',
  USER = 'USER',
  PASSENGER = 'PASSENGER',
  DRIVER = 'DRIVER',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  COMPANY_USER = 'COMPANY_USER',
  SUPERADMIN = 'SUPERADMIN',
}
