export enum PaymentType {
  CASH = 'CASH',
  CARD = 'CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  CUSTOMER_ACCOUNT = 'CUSTOMER_ACCOUNT',
  SAVED_CARD = 'SAVED_CARD',
  VOUCHER = 'VOUCHER',
  COUPON = 'COUPON',
  REFUND = 'REFUND',
}
